const axios = require("axios").default;
const qs = require("qs");
require("dotenv").config();
const { GoogleSpreadsheet } = require("google-spreadsheet");
const { format } = require("date-fns");

const getDoc = async (id, client_email, private_key) => {
  const doc = new GoogleSpreadsheet(id);
  await doc.useServiceAccountAuth({
    // env var values are copied = require(" service account credentials generated by google
    // see "Authentication" section in docs for more info
    client_email: client_email,
    private_key: private_key.replace(/\\n/g, "\n"),
  });
  const info = await doc.loadInfo();
  return doc;
};
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

const data = qs.stringify({
  grant_type: "client_credentials",
  scopes: "PublicApi.Access",
  client_id: "9574dedd-d678-43c3-82d4-1b46769a3706",
  client_secret: "6929FC95B88207276B9A0EB07EBA89575489224E",
});
const authConfig = {
  method: "post",
  url: "https://id.kiotviet.vn/connect/token",
  headers: {
    "Content-Type": "application/x-www-form-urlencoded",
  },
  data: data,
};
module.exports = {
  getDoc,
  sleep,
  authConfig,
};
