export const webhook = async (req, res) => {
  try {
    const doc = new GoogleSpreadsheet(
      '1RzTedxhXeK3OJq4RXs41HrgZj0gP1hlRrlsgkgpOfwo'
    );

    // Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
    await doc.useServiceAccountAuth({
      // env var values are copied from service account credentials generated by google
      // see "Authentication" section in docs for more info
      client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
      private_key: process.env.GOOGLE_PRIVATE_KEY,
    });

    await doc.loadInfo(); // loads document properties and worksheets
    switch (req.body.event_name) {
      case 'user_send_text':
        const sheet = doc.sheetsByIndex[0];
        await sheet.addRows([
          { userId: req.body.user_id_by_app, message: req.body?.message?.text },
        ]);
        return res.json({ message: 'Success' });

      default:
        break;
    }

    return res.json({ message: 'webhook' });
  } catch (error) {
    console.log('error', error);
  }
};
